openapi: 3.0.1
info:
  title: wordsComparer - API для сравнения слов
  description: >-
    API для сравнения 2-х созвучных слов. Принимает 2 слова, выдаёт либо true/false, либо развёрнутый ответ
  version: 1.0.0
  contact:
    name: Ayrat Sungatullin
    url: https://github.com/proger-coder/wordsComparer
    email: dimanvaz04@gmail.com
servers:
  - url: http://localhost:33/
    description: основной сервер на локалхосте
paths:
  /:
    get:
      summary: Получить информацию о статусе сервиса
      responses:
        200:
          description: страница с информацией о сервисе
          content:
            text/html:
              schema:
                type: string
  /only_boolean:
    post:
      summary: Проверить совпадение двух слов
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                given:
                  type: string
                answer:
                  type: string
                limit:
                  type: integer
                  default: 2
      responses:
        200:
          description: Результат проверки
          content:
            application/json:
              schema:
                type: object
                properties:
                  match:
                    type: boolean
        400:
          description: Отсутствует JSON или необходимые данные в запросе
  /full_info:
    post:
      summary: Получить полную информацию о сравнении двух слов
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                given:
                  type: string
                answer:
                  type: string
      responses:
        200:
          description: Результат сравнения
          content:
            application/json:
              schema:
                type: object
                properties:
                  given_word:
                    type: string
                  answer_word:
                    type: string
                  distance:
                    type: integer
        400:
          description: Отсутствует JSON или необходимые данные в запросе
